### ISSUE TITLE
Mothur 1.43.2 adds in more parameters to fasta file

### ISSUE THREAD

**Issue by kevans27** [McMahonLab/16STaxAss#111]
Hi all!

I realized that I was having trouble running some of the python scripts in steps 7 and 8 because of the recent mothur update. Specifically, after the sequence name, mothur 1.43 puts in a tab and then a single string of the samples that the sequence is found in. This caused the sequence names read from my otus.fasta file to be outrageously long and wrong, which causes a key mismatch when trying to align match to the id files. I got around this by creating my keys from the otus.fasta file in steps 7 and 8 by splitting the line by tab, choosing the first item, and finally removing the ">". I think(?) that should be general across mothur versions, in case anyone else is sharing my problem.

I also may have done something weird in mothur to cause this. I'm pretty new there

-Kate

**Comment by rrohwer** [comment]
Thanks so much for the issue report! It sounds like your text parsing is a good fix, and I will try to add it to the taxass scripts soon (after I update mothur!).

**Comment by kevans27** [comment]
Great! Thank you!!

**Comment by rrohwer** [comment]
Hi everyone, these bugs are stemming from problems with how the sequence IDs are named. Ideally, you would edit that during step 0's file formatting instead of later when the error appears, but im so glad you were able to troubleshoot the problems yourself! It's possible that the sequence ID names changed in the new mothur output, but this would have happened before taxass. The taxass workflow itself is still fully compatible as long as sequence IDs follow all the format rules in the directions. I tested it with new mothur, new blast, and new R =)

**Comment by rrohwer** [comment]
note that the new reformat_fasta.R will clean out everything after white space from the fasta seqID lines, so this will be easy to fix now.
