### ISSUE TITLE
Step 6-7: Biopython

### ISSUE THREAD

**Issue by joshamilton** [McMahonLab/16STaxAss#32]
Both Python scripts implicitly assume a FASTA file structure with sequence IDs and sequences alternating lines. There is no reason this would be the case in all FASTA files, and the files I have do not adhere to this convention. Instead of reading these files in ourselves, consider using BioPython, which has broad support for working with sequence files. Would also alleviate some of the burden on users to ensure their FASTA files are properly formatted.

**Comment by rrohwer** [comment]
I thought that the definition of a fasta file was that structure?

I guess if it works it's better, but I can think of 2 concerns:
1. do we worry about too many program dependencies?  Will people have to download that and get it to work also?  python was just already on my computer I didn't have to do anything to use it.  
2. the file structure issue is more for the BLAST results.  because BLAST will abbreviate your seqID if it's long, but then the sorted seqIDs need to be matched back to the origional seqIDs to make the sorted fasta files.  But we definitely _should_ figure out how exactly BLAST changed ID names.  I just noticed it did once and said, "oh, make it simple!" but I don't actually know when exactly it will do that.

**Comment by mcmahon-uw** [comment]
Not sure if you have moved past this already, but one option is to re-name your tag sequences. The FASTX toolkit has a program to do this quickly and easily. In general I think it's a good idea since the read names coming off the Illumina machine are crazy long and probably double (?) the size of the fasta file in some cases???

http://hannonlab.cshl.edu/fastx_toolkit/

On Nov 4, 2015, at 7:42 PM, rrohwer <notifications@github.com<mailto:notifications@github.com>> wrote:

I thought that the definition of a fasta file was that structure?

I guess if it works it's better, but I can think of 2 concerns:
1.  do we worry about too many program dependencies? Will people have to download that and get it to work also? python was just already on my computer I didn't have to do anything to use it.
2.  the file structure issue is more for the BLAST results. because BLAST will abbreviate your seqID if it's long, but then the sorted seqIDs need to be matched back to the origional seqIDs to make the sorted fasta files. But we definitely should figure out how exactly BLAST changed ID names. I just noticed it did once and said, "oh, make it simple!" but I don't actually know when exactly it will do that.

—
Reply to this email directly or view it on GitHubhttps://github.com/McMahonLab/16STaxAss/issues/32#issuecomment-153926698.

---

Katherine (Trina) McMahon, Professor
Goddess of Funkosity
Vilas Distinguished Achievement Professor
Departments of Civil and Environmental Engineering and Bacteriology
Co-Faculty Director, Delta Program (http://www.delta.wisc.edu)
University of Wisconsin - Madison, Madison, WI  53706-1691

Office:  5552 Microbial Sciences Building (MSB)
Lab:  5525 MSB
Website:  http://mcmahonlab.wisc.edu/

## Google Scholar: https://scholar.google.com/citations?user=SaAIxywAAAAJ&hl=en

**Comment by rrohwer** [comment]
follow-up:  @joshamilton, the scripts use biopython now and are much awesomer, right?  Should we close the issue?

**Comment by joshamilton** [comment]
@rrohwer They currently do not, but I will rewrite them to use Biopython. For R, the package [Bioconductor](https://www.bioconductor.org/help/workflows/high-throughput-sequencing/) supports reading of sequences files, which I suggest we use as well.

**Comment by rrohwer** [comment]
Good to know about Bioconductor, but for now none of the R scripts read
sequence files.  I was trying to avoid forcing fastas into matrices b/c R
can be so weird with file import, so that's why I struggled on with those
python scripts.

On Sat, Jan 16, 2016 at 7:04 PM, Joshua J Hamilton <notifications@github.com
